logging_env: CLOUD
level: DEBUG
webhook_url: https://discordapp.com/api/webhooks/1120189909978857622/PukSc8P0K0rpQjhxmTGwVeotThdr6g4Pm5uEyBzjIYDQvKzZtk6hBWwLIVW33Tr5XhCq
game_ids:
  - g5d6db25646d0
poll_interval: 5
dry_run: false
