logging_env: CLOUD
level: DEBUG
webhook_url: https://discordapp.com/api/webhooks/1120189909978857622/PukSc8P0K0rpQjhxmTGwVeotThdr6g4Pm5uEyBzjIYDQvKzZtk6hBWwLIVW33Tr5XhCq
game_ids:
  - g153f56027107
  - ge9b54045cfdf
poll_interval: 5
dry_run: false
