# webhook_url: https://discordapp.com/api/webhooks/1120189909978857622/PukSc8P0K0rpQjhxmTGwVeotThdr6g4Pm5uEyBzjIYDQvKzZtk6hBWwLIVW33Tr5XhCq
webhook_url: https://discord.com/api/webhooks/1116176985698353234/fl9gZeaX1Rzvmec4sSkDRS4gtg6cb12PubyZwEyMAZ0f9tDzjstrN38rovyVOEsFD7Bz
game_url: https://terraforming-mars.herokuapp.com/api/game?id=g153f56027107
