logging_env: CLOUD
webhook_url: https://discord.com/api/webhooks/1116176985698353234/fl9gZeaX1Rzvmec4sSkDRS4gtg6cb12PubyZwEyMAZ0f9tDzjstrN38rovyVOEsFD7Bz
game_ids:
  - g153f56027107
  - ge9b54045cfdf
dry_run: false
