logging_env: CLOUD
webhook_url: https://discord.com/api/webhooks/1122015189773058098/d2RpogKb8oZpoRy81dIdUPZos-GXizii3lbm2kQkuEVGiEFBuyfbE_xpJQecl1tKpwVv
game_ids:
  - g153f56027107
  - ge9b54045cfdf
dry_run: false
